from __future__ import annotations

import inspect
import keyword
import re
from datetime import datetime
from pathlib import Path

from quickdb import Server, SQLDatabase


def _to_pascal_case(name: str) -> str:
    return ''.join(word.capitalize() for word in name.split('_'))


def _class_to_filename(class_name: str) -> str:
    s = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', class_name)
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s)
    return s.lower() + '.pyi'


def _generate_table_stub(table_name: str, columns: list[str]) -> str:
    class_name = f'_{_to_pascal_case(table_name)}Table'
    safe_cols = [c for c in columns if c.isidentifier() and not keyword.iskeyword(c)]

    col_attrs = '\n'.join(f'    {col}: str' for col in safe_cols)

    if safe_cols:
        literal_fields = ', '.join(f"'{col}'" for col in safe_cols)
        fields_type = f'list[Literal[{literal_fields}]] | None'
    else:
        fields_type = 'list[str] | None'

    method = (
        f'    def limited_query(\n'
        f'        self,\n'
        f'        fields: {fields_type} = None,\n'
        f'        where: list[str] | None = None,\n'
        f'        limit: int = 10,\n'
        f'    ) -> pd.DataFrame: ...'
    )

    body = f'{col_attrs}\n\n{method}' if col_attrs else method
    return f'class {class_name}:\n{body}\n'


def _generate_database_stub(db_name: str, table_names: list[str]) -> str:
    class_name = f'_{_to_pascal_case(db_name)}Db'
    safe_tables = [t for t in table_names if t.isidentifier() and not keyword.iskeyword(t)]
    if safe_tables:
        body = '\n'.join(f'    {t}: _{_to_pascal_case(t)}Table' for t in safe_tables)
    else:
        body = '    pass'
    return f'class {class_name}(SQLDatabase):\n{body}\n'


def _generate_file_header(parent_module: str, parent_class_name: str) -> str:
    timestamp = datetime.now().isoformat(timespec='seconds')
    return (
        f'# AUTO-GENERATED by quickdb StubGenerator — do not edit by hand\n'
        f'# Generated: {timestamp}\n'
        f'\n'
        f'import pandas as pd\n'
        f'from typing import Literal\n'
        f'from quickdb import SQLDatabase\n'
        f'from {parent_module} import {parent_class_name}\n'
    )


class StubGenerator:
    def __init__(self, server: Server) -> None:
        self.server = server
        self._server_file = Path(inspect.getfile(type(server)))

    def generate(self) -> Path:
        deep_schema: dict[str, dict[str, list[str]]] = {}
        for db_name in self.server.my_databases:
            db: SQLDatabase = getattr(self.server, db_name)
            deep_schema[db_name] = {
                table.name: list(table.columns.keys())
                for table in db._base.metadata.tables.values()
            }

        surface_dbs = [
            db for db in self.server.get_available_dbs()
            if db not in self.server.my_databases
        ]

        parent_cls = type(self.server).__bases__[0]
        server_class_name = type(self.server).__name__

        sig = inspect.signature(type(self.server))
        clean_sig = sig.replace(return_annotation=inspect.Parameter.empty)
        params_str = str(clean_sig)[1:-1]  # strip surrounding parens
        init_sig = f'self, {params_str}' if params_str else 'self'
        server_init = f'    def __init__({init_sig}) -> None: ...'

        content = self._build_content(
            server_class_name=server_class_name,
            parent_class_name=parent_cls.__name__,
            parent_module=parent_cls.__module__,
            deep_schema=deep_schema,
            surface_dbs=surface_dbs,
            server_init=server_init,
        )

        output_file = self._server_file.with_suffix('.pyi')
        output_file.write_text(content, encoding='utf-8')
        return output_file

    def _build_content(
        self,
        server_class_name: str,
        parent_class_name: str,
        parent_module: str,
        deep_schema: dict[str, dict[str, list[str]]],
        surface_dbs: list[str],
        server_init: str,
    ) -> str:
        sep = '─' * 50
        parts: list[str] = [_generate_file_header(parent_module, parent_class_name)]

        if deep_schema:
            parts += [f'# ── Deep stubs (my_databases) {sep}', '']
            for db_name, tables in deep_schema.items():
                for table_name, columns in tables.items():
                    parts += [_generate_table_stub(table_name, columns), '']
                parts += [_generate_database_stub(db_name, list(tables.keys())), '']

        parts += [f'# ── Server {sep}', '']
        parts.append(_generate_server_stub(
            server_class_name=server_class_name,
            parent_class_name=parent_class_name,
            deep_db_names=list(deep_schema.keys()),
            surface_db_names=surface_dbs,
            server_init=server_init,
        ))

        return '\n'.join(parts)


def _generate_server_stub(
    server_class_name: str,
    parent_class_name: str,
    deep_db_names: list[str],
    surface_db_names: list[str],
    server_init: str | None = None,
) -> str:
    safe_deep = [n for n in deep_db_names if n.isidentifier() and not keyword.iskeyword(n)]
    safe_surface = [n for n in surface_db_names if n.isidentifier() and not keyword.iskeyword(n)]

    lines = [f'class {server_class_name}({parent_class_name}):']

    if server_init:
        lines.append(server_init)

    if safe_deep:
        lines.append('    # fully stubbed')
        for db_name in safe_deep:
            lines.append(f'    {db_name}: _{_to_pascal_case(db_name)}Db')

    if safe_surface:
        lines.append('    # available — add to my_databases for full stubs')
        for db_name in safe_surface:
            lines.append(f'    {db_name}: SQLDatabase')

    if not server_init and not safe_deep and not safe_surface:
        lines.append('    pass')

    return '\n'.join(lines) + '\n'
