from __future__ import annotations

import keyword
import re
from datetime import datetime
from pathlib import Path

from quickdb.core.database import SQLDatabase
from quickdb.core.server import Server
from quickdb.core.table import SQLTable


def _to_pascal_case(name: str) -> str:
    return ''.join(word.capitalize() for word in name.split('_'))


def _class_to_filename(class_name: str) -> str:
    s = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', class_name)
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s)
    return s.lower() + '.pyi'


def _generate_table_stub(table_name: str, columns: list[str]) -> str:
    class_name = f'_{_to_pascal_case(table_name)}Table'
    safe_cols = [c for c in columns if c.isidentifier() and not keyword.iskeyword(c)]

    col_attrs = '\n'.join(f'    {col}: str' for col in safe_cols)

    if safe_cols:
        literal_fields = ', '.join(f"'{col}'" for col in safe_cols)
        fields_type = f'list[Literal[{literal_fields}]] | None'
    else:
        fields_type = 'list[str] | None'

    method = (
        f'    def limited_query(\n'
        f'        self,\n'
        f'        fields: {fields_type} = None,\n'
        f'        where: list[str] | None = None,\n'
        f'        limit: int = 10,\n'
        f'    ) -> pd.DataFrame: ...'
    )

    body = f'{col_attrs}\n\n{method}' if col_attrs else method
    return f'class {class_name}(SQLTable):\n{body}\n'


def _generate_database_stub(db_name: str, table_names: list[str]) -> str:
    class_name = f'_{_to_pascal_case(db_name)}Db'
    safe_tables = [t for t in table_names if t.isidentifier() and not keyword.iskeyword(t)]
    if safe_tables:
        body = '\n'.join(f'    {t}: _{_to_pascal_case(t)}Table' for t in safe_tables)
    else:
        body = '    pass'
    return f'class {class_name}(SQLDatabase):\n{body}\n'


def _generate_file_header(parent_module: str, parent_class_name: str) -> str:
    timestamp = datetime.now().isoformat(timespec='seconds')
    return (
        f'# AUTO-GENERATED by quickdb StubGenerator — do not edit by hand\n'
        f'# Generated: {timestamp}\n'
        f'\n'
        f'import pandas as pd\n'
        f'from typing import Literal\n'
        f'from quickdb import SQLDatabase, SQLTable\n'
        f'from {parent_module} import {parent_class_name}\n'
    )


def _generate_server_stub(
    server_class_name: str,
    parent_class_name: str,
    deep_db_names: list[str],
    surface_db_names: list[str],
) -> str:
    lines = [f'class {server_class_name}({parent_class_name}):']

    if deep_db_names:
        lines.append('    # fully stubbed')
        for db_name in deep_db_names:
            lines.append(f'    {db_name}: _{_to_pascal_case(db_name)}Db')

    if surface_db_names:
        lines.append('    # available — add to my_databases for full stubs')
        for db_name in surface_db_names:
            lines.append(f'    {db_name}: SQLDatabase')

    if not deep_db_names and not surface_db_names:
        lines.append('    pass')

    return '\n'.join(lines) + '\n'
