from quickdb.scripts.stub_generator import _class_to_filename, _to_pascal_case


def test_to_pascal_case_single_word():
    assert _to_pascal_case('cases') == 'Cases'


def test_to_pascal_case_snake_case():
    assert _to_pascal_case('case_updates') == 'CaseUpdates'


def test_to_pascal_case_single_segment():
    assert _to_pascal_case('suitecrm') == 'Suitecrm'


def test_to_pascal_case_multi_segment():
    assert _to_pascal_case('my_warehouse') == 'MyWarehouse'


def test_class_to_filename_sqlserver():
    assert _class_to_filename('SQLServer') == 'sql_server.pyi'


def test_class_to_filename_suitecrm():
    assert _class_to_filename('SuiteCRMServer') == 'suite_crm_server.pyi'


def test_class_to_filename_mariadb():
    assert _class_to_filename('MariaDBServer') == 'maria_db_server.pyi'


def test_class_to_filename_simple():
    assert _class_to_filename('MyServer') == 'my_server.pyi'


from quickdb.scripts.stub_generator import _generate_table_stub


def test_table_stub_class_name():
    result = _generate_table_stub('cases', ['id', 'name'])
    assert 'class _CasesTable:' in result


def test_table_stub_snake_case_name():
    result = _generate_table_stub('case_updates', ['id'])
    assert 'class _CaseUpdatesTable:' in result


def test_table_stub_column_attrs():
    result = _generate_table_stub('cases', ['id', 'name', 'entered_date'])
    assert '    id: str' in result
    assert '    name: str' in result
    assert '    entered_date: str' in result


def test_table_stub_literal_fields_in_limited_query():
    result = _generate_table_stub('cases', ['id', 'name'])
    assert "Literal['id', 'name']" in result
    assert '-> pd.DataFrame: ...' in result


def test_table_stub_skips_python_keywords():
    result = _generate_table_stub('orders', ['id', 'from', 'return'])
    assert '    id: str' in result
    assert '    from: str' not in result
    assert '    return: str' not in result


def test_table_stub_skips_non_identifiers():
    result = _generate_table_stub('orders', ['id', '1bad', 'has space'])
    assert '    id: str' in result
    assert '    1bad: str' not in result
    assert '    has space: str' not in result


def test_table_stub_no_valid_columns_uses_generic_fields_type():
    result = _generate_table_stub('orders', ['from', 'return'])
    assert 'list[str] | None' in result
    assert 'Literal' not in result


from quickdb.scripts.stub_generator import _generate_database_stub


def test_database_stub_class_name():
    result = _generate_database_stub('suitecrm', ['cases', 'accounts'])
    assert 'class _SuitecrmDb(SQLDatabase):' in result


def test_database_stub_snake_case_name():
    result = _generate_database_stub('my_warehouse', ['orders'])
    assert 'class _MyWarehouseDb(SQLDatabase):' in result


def test_database_stub_table_attrs():
    result = _generate_database_stub('suitecrm', ['cases', 'accounts'])
    assert '    cases: _CasesTable' in result
    assert '    accounts: _AccountsTable' in result


def test_database_stub_no_tables_emits_pass():
    result = _generate_database_stub('empty_db', [])
    assert 'class _EmptyDbDb(SQLDatabase):' in result
    assert '    pass' in result


def test_database_stub_skips_keyword_table_names():
    result = _generate_database_stub('mydb', ['orders', 'from', 'global'])
    assert '    orders: _OrdersTable' in result
    assert '    from: _FromTable' not in result
    assert '    global: _GlobalTable' not in result


from quickdb.scripts.stub_generator import _generate_file_header, _generate_server_stub


def test_file_header_contains_banner():
    result = _generate_file_header('quickdb.core.server', 'MariaDBServer')
    assert '# AUTO-GENERATED by quickdb StubGenerator' in result
    assert 'do not edit by hand' in result


def test_file_header_imports():
    result = _generate_file_header('quickdb.core.server', 'MariaDBServer')
    assert 'import pandas as pd' in result
    assert 'from typing import Literal' in result
    assert 'from quickdb import SQLDatabase' in result
    assert 'from quickdb.core.server import MariaDBServer' in result


def test_file_header_uses_correct_parent_module():
    result = _generate_file_header('mypackage.servers', 'PostgreSQLServer')
    assert 'from mypackage.servers import PostgreSQLServer' in result


def test_server_stub_class_definition():
    result = _generate_server_stub('SuiteCRMServer', 'MariaDBServer', ['suitecrm'], ['mysql'])
    assert 'class SuiteCRMServer(MariaDBServer):' in result


def test_server_stub_deep_db_attribute():
    result = _generate_server_stub('SuiteCRMServer', 'MariaDBServer', ['suitecrm'], [])
    assert '    suitecrm: _SuitecrmDb' in result


def test_server_stub_surface_db_attribute():
    result = _generate_server_stub('SuiteCRMServer', 'MariaDBServer', [], ['information_schema'])
    assert '    information_schema: SQLDatabase' in result
    assert 'add to my_databases for full stubs' in result


def test_server_stub_deep_and_surface_sections():
    result = _generate_server_stub(
        'SuiteCRMServer', 'MariaDBServer', ['suitecrm'], ['information_schema', 'mysql']
    )
    assert '    suitecrm: _SuitecrmDb' in result
    assert '    information_schema: SQLDatabase' in result
    assert '    mysql: SQLDatabase' in result


def test_server_stub_empty_emits_pass():
    result = _generate_server_stub('MyServer', 'SQLServer', [], [])
    assert '    pass' in result


def test_server_stub_init_suppresses_pass():
    result = _generate_server_stub('MyServer', 'SQLServer', [], [], server_init='    def __init__(self) -> None: ...')
    assert '    pass' not in result
    assert 'def __init__' in result


def test_server_stub_init_appears_before_db_attrs():
    result = _generate_server_stub(
        'MyServer', 'SQLServer', ['mydb'], [], server_init='    def __init__(self, cache_all: bool = False) -> None: ...'
    )
    init_pos = result.index('def __init__')
    db_pos = result.index('mydb:')
    assert init_pos < db_pos


def test_server_stub_skips_keyword_db_names():
    result = _generate_server_stub('MyServer', 'SQLServer', ['mydb', 'from'], ['other', 'class'])
    assert '    mydb: _MydbDb' in result
    assert '    other: SQLDatabase' in result
    assert '    from: _FromDb' not in result
    assert '    class: SQLDatabase' not in result


from unittest.mock import MagicMock, patch

from quickdb.core.server import MariaDBServer
from quickdb.scripts.stub_generator import StubGenerator


class SuiteCRMServer(MariaDBServer):
    """Test double — represents a child server subclass."""
    my_databases: list = []


def _make_mock_db(tables: dict[str, list[str]]) -> MagicMock:
    """Build a mock SQLDatabase whose metadata contains the given tables and columns."""
    mock_tables = []
    for table_name, col_names in tables.items():
        mt = MagicMock()
        mt.name = table_name
        mt.columns.keys.return_value = col_names
        mock_tables.append(mt)
    mock_db = MagicMock()
    mock_db._base.metadata.tables.values.return_value = mock_tables
    return mock_db


def _make_test_server(
    my_databases: list[str] | None = None,
    available_dbs: list[str] | None = None,
    deep_tables: dict[str, list[str]] | None = None,
) -> SuiteCRMServer:
    my_databases = my_databases if my_databases is not None else ['suitecrm']
    available_dbs = available_dbs if available_dbs is not None else ['suitecrm', 'information_schema', 'mysql']
    deep_tables = deep_tables if deep_tables is not None else {'cases': ['id', 'name']}

    inst = object.__new__(SuiteCRMServer)
    inst.my_databases = my_databases
    inst._databases = {db: _make_mock_db(deep_tables) for db in my_databases}
    inst.get_available_dbs = lambda: available_dbs
    return inst


def test_stub_generator_writes_pyi_file(tmp_path):
    server = _make_test_server()
    with patch('inspect.getfile', return_value=str(tmp_path / 'server.py')):
        output = StubGenerator(server).generate()
        assert output.exists()
        assert output.suffix == '.pyi'
        assert output.name == 'server.pyi'


def test_stub_generator_deep_db_in_output(tmp_path):
    server = _make_test_server()
    with patch('inspect.getfile', return_value=str(tmp_path / 'server.py')):
        output = StubGenerator(server).generate()
        content = output.read_text()
        assert 'class _CasesTable:' in content
        assert 'class _SuitecrmDb(SQLDatabase):' in content
        assert '    suitecrm: _SuitecrmDb' in content
        assert "Literal['id', 'name']" in content


def test_stub_generator_surface_dbs_in_output(tmp_path):
    server = _make_test_server()
    with patch('inspect.getfile', return_value=str(tmp_path / 'server.py')):
        output = StubGenerator(server).generate()
        content = output.read_text()
        assert '    information_schema: SQLDatabase' in content
        assert '    mysql: SQLDatabase' in content
        assert 'add to my_databases for full stubs' in content


def test_stub_generator_correct_parent_import(tmp_path):
    server = _make_test_server(deep_tables={})
    with patch('inspect.getfile', return_value=str(tmp_path / 'server.py')):
        output = StubGenerator(server).generate()
        content = output.read_text()
        assert 'from quickdb.core.server import MariaDBServer' in content
        assert 'class SuiteCRMServer(MariaDBServer):' in content


def test_stub_generator_server_init_in_output(tmp_path):
    server = _make_test_server(deep_tables={})
    with patch('inspect.getfile', return_value=str(tmp_path / 'server.py')):
        output = StubGenerator(server).generate()
        content = output.read_text()
        assert 'def __init__(self' in content
        assert '-> None: ...' in content


def test_stub_generator_returns_path_to_written_file(tmp_path):
    server = _make_test_server(deep_tables={})
    with patch('inspect.getfile', return_value=str(tmp_path / 'server.py')):
        result = StubGenerator(server).generate()
        assert result.is_absolute()
        assert result.exists()


def test_stub_generator_importable_from_quickdb():
    from quickdb import StubGenerator  # noqa: F401
    assert StubGenerator is not None
